stages:
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    env:
      NIFI_WEB_HTTP_PORT: "6666"
  - applyYamlConfig:
      path: ./service.yaml
  - applyYamlConfig:
      path: ./ingress.yaml
timeout: 60
notification: {}
